x-common: &common
  image: ghcr.io/ninanor/fisk-ai:main
  build: .
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  environment:
    DISPLAY: $DISPLAY
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ./input:/app/data/input
    - ./output:/app/data/output
    - ./data/models:/app/data/models:ro

services:
  app:
    <<: *common
    profiles:
      - prod
  test:
    <<: *common
    profiles:
      - test
    command: pixi run test
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./app/logs:/app/app/logs
